import Head from 'next/head'
import Navbar from '../components/Navbar'
import First from '../components/Section_one'
import Third from '../components/Section_three';
import Fourth from '../components/Section_four'
import Fifth from '../components/Section_five'
import Sixth from '../components/Section_six';
import Seven from '../components/Section_seven';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <First />
      <Third />
      <Fourth />
      <Fifth />
      <Sixth />
      <Seven />
    </div>
  )
}


  // git config --global user.email "you@example.com"
  // git config --global user.name "Your Name"